### ISSUE TITLE
"Unhandled Exception" server error and download fails

### ISSUE THREAD

**Issue by teafusion** [rytsikau/ee.Yrewind#64]
I keep getting these errors:

downloading data...
    78% at 0,588 Mbps
Unhandled Exception: System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at yrewind.Saver.FixDownloadM3U(String content, String path)
   at yrewind.Saver.FixCreateMedia(String outputPath, Int32& ffmpegExitCode)
   at yrewind.Saver.Common()
   at yrewind.Program.Main()

Or another example:

downloading data...
    100% at 0,525 Mbps
    12% at 0,398 Mbps
Unhandled Exception: System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at yrewind.Saver.FixDownloadM3U(String content, String path)
   at yrewind.Saver.FixCreateMedia(String outputPath, Int32& ffmpegExitCode)
   at yrewind.Saver.Common()
   at yrewind.Program.Main()

In the latter example the video is obviously complete at 100%, but if I assume correctly the audio stream downloading was interrupted at 12%, which then spoils the whole video. It would be nice if you could ignore audio stream (if that's what it is), when you don't particularly want it.

I try to download one 24h of a stream, 4h segments at the time (to make it nice even 8 segments per day), whereas some 4h segments download fine, some don't download correctly in their entirety even after multiple retries. It wouldn't be possible to complete the incomplete files by downloading only the missing, like you can do with yt-dlp using -c (= continue) flag, would it?

Or should I split the downloads to even smaller segments to avoid wasting 4 hours at the time if an error occurs and file doesn't download complete. It's a bit of more work to create the initial .cmd, copy pasting it and editing copies for desired URLs and dates/times is just find and replace.

The best option would be no errors or merely completing of the incomplete videos by multiple re-downloads, if that's possible to implement to ee.Yrewind.

Here's the URL to the stream I try to download for a weeks worth https://www.youtube.com/watch?v=68ADWiW1zIk

I think I'll try some other stream next for a reference to see if the issue is the same with other streams as well.

Keep up the good work Rytsikau, hope you have time and interest to keep developing this nice piece of stream download helper! 

Seasons Greetings and Happy New Year!

**Comment by teafusion** [comment]
For testing purposes I'm downloading this stream https://www.youtube.com/watch?v=ydYDqZQpim8 with similar script to the other one, but at -r=720p for the speed. The first segment downloaded without any "Unhandled Exception" server error.

**Comment by teafusion** [comment]
It seems to help to download in 60min. rather than 240min. (or 300min.) chunks aka when an error occurs re-downloads are faster and the errors don't seem to be as likely to reoccur, which is bit of a relief.

**Comment by teafusion** [comment]
After downloading about 48hr worth of 60min. segments I can now confirm that shorter segments help a lot in avoiding the server errors in the first place, there has been only few errors and they have all been fixed with the second download. Nice!

If only there was a possibility to set desired length for the segments to use automatically, like -t:60 (-t = trench, in mins.).

**Comment by rytsikau** [comment]
Perhaps your DNS errors are somehow related to the downloading? I would try another as an experiment, such as Google's 8.8.8.8 etc.

When I get around to updating the version, I will definitely make it possible to save the stream without audio.

Also, I remember your time-lapse idea, but I came to the conclusion that there is no point in implementing it yet. The increase in download speed will only appear for timelapses 300x and higher. Do many people need this?

Merry Christmas and Happy New Year!
